#=================================================
#   Description: Build X-WRT using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: x-wrt-master

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        
env:
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: mir3.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo -E apt-get update
        sudo -E apt-get -y install git
        git log -1 --pretty=%B | grep -q "^release:" || (echo "Stop build: not a release commit" >make.log && exit 1)
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      run: git clone --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git

    - name: Update feeds
      run: cd x-wrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd x-wrt && ./scripts/feeds install -a
      
    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE x-wrt/.config
        cat x-wrt/.config
        
    - name: Change default Theme
      run: |
        cd x-wrt
        rm -rf package/lean/luci-theme-neobird
        git clone https://github.com/thinktip/luci-theme-neobird.git package/lean/luci-theme-neobird
        sed -i 's/luci-theme-bootstrap/luci-theme-neobird/' feeds/luci/collections/luci/Makefile

    - name: Building
      run: |
        cp *.sh x-wrt/
        cp release.tag x-wrt/
        cd x-wrt
        echo -e "$(nproc) thread build."
        TARGET=ramips-mt7620 sh build.sh $(nproc)

    - name : Upload make.log if failure
      uses: actions/upload-artifact@master
      if: failure()
      with:
        name: build-failure-log
        path: make.log

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: x-wrt-master=ramips-mt7620
        path: x-wrt/rom
